server:
  port: 8082

spring:
  application:
    name: catalog-service
  audit:
    base-url: ${AUDIT_BASE_URL:http://localhost:8084}
  mongodb:
    uri: mongodb://localhost:27017/catalog

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  info:
    title: Catalog Service API
    version: v1
