apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgres
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_USER
              value: orders
            - name: POSTGRES_PASSWORD
              value: orders
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: orders-postgres
  namespace: shopping
spec:
  selector:
    app: orders-postgres
  ports:
    - port: 5432
      targetPort: 5432
