server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cloud:
    kubernetes:
      discovery:
        all-namespaces: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
